/* 
 * Search for pseudo collision in md5 hash funcion using a birthday attack approach
 */

#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<time.h>

#include"md5.h"
#include"generator.h"

#define BUFFER_SIZE 22          /* The size for create a string representation of a number */
#define WARNS_AFTER 10000       /* Display a warning of status after X repetitions */

#define MAX_EXPONENT 18446744000000000000  /* The maximum number of iteratinons for MD5 */

void parse_arguments(int argc, char *argv[], unsigned int *desired_collision);       /* Function to parse arguments received from stdin */
void display_help_message();                        /* Display the parameters order and how to use properly */

int main(int argc, char *argv[])
{
    unsigned long long int *values;
    char **hashes;
    char buffer[BUFFER_SIZE];
    unsigned char byte_collisions;  /* Counts equal bytes in two hashes */
    unsigned int desired_collision = 0;

    parse_arguments(argc, argv, &desired_collision);    /* Parse the arguments received from stdin */
    const unsigned long long int iterations = calculate_iterations(desired_collision); /* Defines the iterations needed to find a collision */

    values = malloc(sizeof(unsigned long long int) * iterations);
    hashes = malloc(sizeof(char*) * iterations);

    seed_generator();
    printf("==> Generating %lu random messages...\n", iterations);

    clock_t start = clock();

    for (int i = 0; i < iterations; i++){
        values[i] = generate_number(); 
        values[i] = (values[i] << 32) | generate_number();
    }

    printf("==> Hashing all %lu messages...\n", iterations);

    for (int i = 0; i < iterations; i++){
        snprintf(buffer, BUFFER_SIZE, "%ld", values[i]); /* Representing the number as string for hash process */
        hashes[i] = md5(buffer, strlen(buffer));         /* Get the hexadecimal md5 hash */
    }

    printf("==> Searching for collisions in hashes\n");

    for (int i = 0; i < iterations; i++){
        if (i % WARNS_AFTER == 0){
            printf(":: Already checked %d hashes\n", i); 
        }
    
        for (int j = i + 1; j < iterations; j++){
            byte_collisions = 0;

            /* 
             * It's possible to have same numbers being generated by random function.
             * Of course, they are equal, not collision.
            */
            if (values[i] == values[j]){
                continue; 
            }

            /* Check how many bytes are equal */
            for (int k = 0; k < MD5_HEX_DIGEST_SIZE; k++){
                /*
                 * Checks whether it's possible to satisfy the desired collision value with the remaining bytes to test.
                 * Remaining tries + collisions found must be equal or greater than desired collision value.
                 * This prevents to continue test hashes that doesn't satisfy the desired collision value, improving performance.
                */
                if(((MD5_HEX_DIGEST_SIZE - 1) - k) + byte_collisions < desired_collision){
                    break; 
                }

                if ((hashes[i][k] == hashes[j][k])){
                    byte_collisions++;
                } 
            }

            if(byte_collisions >= desired_collision){
                printf("==> %d bytes collision found!!!! Iteration: %d\n", byte_collisions, i);
                printf("md5('%ld')\t==\t%s\nmd5('%ld')\t==\t%s\n", values[i], hashes[i], values[j], hashes[j]);
            }
        }
    }

    printf("Finished search for collision\n");
    printf("Time elapsed: %f seconds\n", ((double)clock() - start) / CLOCKS_PER_SEC);
    printf("Time elapsed: %f minutes\n", (((double)clock() - start) / CLOCKS_PER_SEC) / 60);
    printf("Time elapsed: %f hours\n", ((((double)clock() - start) / CLOCKS_PER_SEC) / 60) / 60);

    free(hashes);
    free(values);

    return 0;
}

void parse_arguments(int argc, char *argv[], unsigned int *desired_collision)
{
    if (argc < 2){
        display_help_message(argv[0]); 
        exit(1);
    }

    *desired_collision = atoi(argv[1]);
}

void display_help_message(char *program_name)
{
    printf("Usage: %s [desired byte collision]\n", program_name);
    printf("[desired byte collision] = How many bytes must be equal for the hash be considered a collision\n");
}
